### ISSUE TITLE
 2015.10.28 missing on rubygems.org

### ISSUE THREAD

**Issue by mmoll** [Ramaze/ramaze#81]
I don't see it there: https://rubygems.org/gems/ramaze/versions

**Comment by manveru** [comment]
I'll fix that when i get some time to fix the travis issues as well.

**Comment by mmoll** [comment]
Please see mmoll/ramaze@d839110 for some changes, reducing the errors 1 (or 2 on Rubinius), JRuby on travis does not support native extensions (anymore?).

**Comment by manveru** [comment]
Looks good, the error spec fails because the middleware changed, but I can fix that when I get a little bit of time tonight.

**Comment by mmoll** [comment]
closing, as the initial underlying problem doesn't affect me anymore.
