### ISSUE TITLE
End support for localmemcache

### ISSUE THREAD

**Issue by mfaughn** [Ramaze/ramaze#93]
localmemcache doesn't play nicely with OSX.  The localmemcache gem appears to be defunct.  Its homepage is gone and it hasn't been updated since 2009.  I also see that it is only a development dependency for JRuby.  The most recent version of the gem has been downloaded only ~30K times since 2009.  I propose removing localmemcache from Ramaze.  Alternatively, leave it in but throw a warning that says it's continued use is unsupported and untested?

**Comment by manveru** [comment]
I really doubt anybody will miss it :)

**Comment by Pistos** [comment]
Sounds good to me, as long as it doesn't really break anything, or is replaced with an equivalent (unless this is one of several alternatives).

**Comment by mfaughn** [comment]
It is (was) one of several alternatives.
